version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - gis_1ban_01_network
    volumes:
    - gis_1ban_01_static:/data/static/
    - gis_1ban_01_media:/data/media/
    - /home/kyeongseojeon/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80

  django:
    image: gis_1ban_01_django:5
    networks:
      - gis_1ban_01_network
    volumes:
    - gis_1ban_01_static:/home/2th-uebung/staticfiles/
    - gis_1ban_01_media:/home/2th-uebung/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_1ban_01_network
    volumes:
      - gis_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD


networks:
  gis_1ban_01_network:

volumes:
  gis_1ban_01_static:
  gis_1ban_01_media:
  gis_mariadb:

secrets:
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  DJANGO_SECRET_KEY:
    external: true