version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - gis_1ban_01_network
    volumes:
    - gis_1ban_01_static:/data/static/
    - gis_1ban_01_media:/data/media
    - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80

  django:
    image: gis_1ban_01_django:3
    networks:
      - gis_1ban_01_network
    volumes:
    - gis_1ban_01_static:/home/2th-uebung/staticfiles/
    - gis_1ban_01_media:/home/2th-uebung/media/

networks: #네트워크 생성
  gis_1ban_01_network:

volumes:  # 볼륨생성
  gis_1ban_01_static:
  gis_1ban_01_media: